config/routes.rb
Rails.application.routes.draw do
  resources :politics

  root to: 'politics#index'
end

app/models/politic.rb
class Politic < ApplicationRecord
  has_many :careers
  has_many :declared_goods
  has_many :judicial_processes
  has_many :proposals
end

app/controllers/politics_controller.rb
class PoliticsController < ApplicationController
  before_action :set_politic, only: [:show, :edit, :update, :destroy]

  # GET /politics
  # GET /politics.json
  def index
    @politics = Politic.all
  end

  # GET /politics/1
  # GET /politics/1.json
  def show
    @politic = Politic.find(params[:id])
  end

  # GET /politics/new
  def new
    @politic = Politic.new
  end

  # GET /politics/1/edit
  def edit
  end

  # POST /politics
  # POST /politics.json
  def create
    @politic = Politic.new(politic_params)

    respond_to do |format|
      if @politic.save
        format.html { redirect_to :politics, notice: 'Politic was successfully created.' }
        format.json { render :show, status: :created, location: @politic }
      else
        format.html { render :new }
        format.json { render json: @politic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /politics/1
  # PATCH/PUT /politics/1.json
  def update
    respond_to do |format|
      if @politic.update(politic_params)
        format.html { redirect_to @politic, notice: 'Politic was successfully updated.' }
        format.json { render :show, status: :ok, location: @politic }
      else
        format.html { render :edit }
        format.json { render json: @politic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /politics/1
  # DELETE /politics/1.json
  def destroy
    @politic.destroy
    respond_to do |format|
      format.html { redirect_to politics_url, notice: 'Politic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_politic
      @politic = Politic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def politic_params
      params.require(:politic).permit(:name, :age, :state, :city, :part)
    end
end

app/helpers/politics_helper.rb
module PoliticsHelper
end

app/views/politics/_form.html.erb
<%= form_with(model: politic, local: true) do |form| %>
  <% if politic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(politic.errors.count, "error") %> prohibited this politic from being saved:</h2>

      <ul>
      <% politic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.label :name %>
  <%= form.text_field :name %>

  </br>

  <%= form.label :age %>
  <%= form.text_field :age %>

  </br>

  <%= form.label :state %>
  <%= form.text_field :state %>

  </br>

  <%= form.label :city %>
  <%= form.text_field :city %>

  </br>

  <%= form.label :part %>
  <%= form.text_field :part %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/politics/edit.html.erb
<h1>Editing Politic</h1>

<%= render 'form', politic: @politic %>

<%= link_to 'Show', @politic %> |
<%= link_to 'Back', politics_path %>

app/views/politics/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <div class="box-widget widget-module">
        <div class="widget-container">
          <div class="widget-block">
            <div class="table-responsive">
              <table class="table table-hover table-bordered matmix-dt bg-hc-border">
                <thead>
                  <tr>
                    <th colspan="7">
                      <div class="dt-col-header">Políticos</div>
                      <p>
                        This is a example of a complex header table you can use this syle in any kind of table.
                      </p>
                    </th>
                  </tr>
                  <tr>
                    <th class="tc-center">
                    </th>
                    <th>
                      Nome
                    </th>
                    <th>
                      Idade
                    </th>
                    <th class="tc-center">
                      Estado
                    </th>
                    <th class="tc-center">
                      Cidade
                    </th>
                    <th class="tc-center">
                      Partido
                    </th>
                    <th class="tc-center">
                      Action
                    </th>
                  </tr>
                </thead>
                <tbody>
                  <% @politics.each do |politic| %>
                    <tr>
                      <td class="tc-center">
                        <%= link_to politic_path(politic), class: "user-td-thumb" do %>
                          <img src="images/avatar/adellecharles.jpg" alt="user">
                        <% end %>
                      </td>
                      <td>
                        <%= politic.name %>
                      </td>
                      <td>
                        <%= politic.age %>
                      </td>
                      <td class="tc-center">
                        <%= politic.state %>
                      </td>
                      <td class="tc-center">
                        <%= politic.city %>
                      </td>
                      <td class="tc-center">
                        <%= politic.part %>
                      </td>
                      <td class="tc-center">
                        <div class="btn-toolbar" role="toolbar">
                          <div class="btn-group" role="group">
                            <a href="#" class="btn btn-default btn-sm m-user-edit">Edit</a>
                            <a href="#" class="btn btn-default btn-sm m-user-delete">Delete</a>
                          </div>
                        </div>
                      </td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
          </div>
          <div class="dt-pagination">
            <nav>
              <ul class="pagination">
                <li>
                  <a href="#" aria-label="Previous">
                    <span aria-hidden="true">Prev</span>
                  </a>
                </li>
                <li>
                  <a href="#">1</a>
                </li>
                <li>
                  <a href="#">2</a>
                </li>
                <li>
                  <a href="#">3</a>
                </li>
                <li>
                  <a href="#">4</a>
                </li>
                <li>
                  <a href="#">5</a>
                </li>
                <li>
                  <a href="#" aria-label="Next">
                    <span aria-hidden="true">Next</span>
                  </a>
                </li>
              </ul>
            </nav>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/politics/new.html.erb
<h1>New Politic</h1>

<%= render 'form', politic: @politic %>

<%= link_to 'Back', politics_path %>

app/views/politics/show.html.erb
<div class="container-fluid">
  <div class="forum-header">
    <div class="row">
      <div class="col-md-8">
        <div>
          <label class="label label-success">
            <%= @politic.part %>
          </label>
        </div>
        <h2 class="forum-title"><%= @politic.name %></h2>
        <p class="forum-sub-title">
          <span class="topic-meta">
            Candidato a presidência da republica
          </span>
        </p>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-4">
      <div class="iconic-w-horizontal w_bg_deep_orange light-text">
        <a href="#" class="ico-block">
          <span><i class="ico-users"></i></span>
        </a>
        <div class="w-meta-info number-rotate">
          <span class="w-meta-value number-animate">
            <%= number_to_currency(@politic.declared_goods.pluck(:value).sum, locale: 'pt-BR') %>
          </span>
          <span class="w-meta-title">Bens declarados</span>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="iconic-w-horizontal w_bg_green light-text">
        <a href="#" class="ico-block">
          <span><i class="ico-chart"></i></span>
        </a>
        <div class="w-meta-info">
          <span class="w-meta-value number-animate" data-value="20686" data-animation-duration="1500">20,686</span>
          <span class="w-meta-title">New Vistitors</span>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="iconic-w-horizontal w_bg_blue_grey light-text">
        <a href="#" class="ico-block">
          <span><i class="fa fa-mobile fa-2x"></i></span>
        </a>
        <div class="w-meta-info">
          <span class="w-meta-value number-animate" data-value="4500" data-animation-duration="1500">4,500</span>
          <span class="w-meta-title">SMS Sent</span>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="box-widget widget-module">
      <div class="widget-head clearfix">
        <span class="h-icon">
          <i class="fa fa-th"></i>
        </span>
        <h4>Declaração de bens</h4>
        <ul class="widget-action-bar pull-right">
          <li>
              <span class="widget-collapse waves-effect w-collapse"><i class="fa fa-angle-down"></i></span>
          </li>
        </ul>
      </div>
      <div class="widget-container">
        <div class=" widget-block">
          <div id="DataTables_Table_0_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
            <div class="row">
              <div class="col-md-12">
                <div class="td-content">
                  <table class="table table-hover table-bordered matmix-dt bg-hc-border">
                    <thead>
                      <tr>
                        <th colspan="7">
                          <p>
                            Fontes: ****
                          </p>
                        </th>
                      </tr>
                      <tr>
                        <th>
                          Descrição
                        </th>
                        <th>
                          Valor
                        </th>
                      </tr>
                    </thead>
                    <tbody>
                      <% @politic.declared_goods.each do |declared_good| %>
                        <tr>
                          <td>
                            <%= declared_good.description %>
                          </td>
                          <td>
                            <span id="money-mask">
                              <%= number_to_currency(declared_good.value, locale: 'pt-BR') %>
                            </span>
                          </td>
                        </tr>
                      <% end %>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>